import "../../styles/global.css"

import StarPanel, { Intro, SectionLabel, HighlightGrid, Callout, TagRow } from "./StarPanel";

const COLOR = "#7884eb";

interface Props {
  onClose: () => void;
}

export default function Consciousness({ onClose }: Props) {
  return (
    <StarPanel color={COLOR} name="Consciousness" role="Subjective Experience" onClose={onClose}>
      <SectionLabel>Questions I sit with</SectionLabel>
      <div id="body">
            <h1>Consciousness</h1>
            <p>My views on consciousness have been heavily influenced by Doug Hofstadter's <i>I am a Strange Loop</i>. To avoid simply summarizing that book, I will urge to you read it. It's awesome. I will use this page to instead think about some things that the book didn't cover.</p>
            <h2>What is a Conscious Experience?</h2>
            <p>My understanding of a conscious experience is as follows: living, conscious creatures have a subjective inner world that percieves the objective outer world. That perception takes place in the form of a conscious experience. When you see an apple, you are consciously experiencing that apple through your sense of sight. The same can be true for taste, touch, smell, etc. What is this perception though? How does it relate to the physical world? Here I intend to think about this topic.</p>
            <h2>Communicating Conscious Experiences</h2>
            <p>One of the most vexing aspects of conscious experiences is that they are seemingly incommunicable. No string of letters that I could put together on this page will ever effectively describe a conscious experience. I can't make a blind person see red just by describing it. I can't describe how pain feels to someone who's never felt pain. Does this mean its impossible to describe it to someone effectively?</p>
            <p>What if it is a fundamental aspect of conscious experience that it can't be communicated with language? I want to look at other ways that a conscious experience could be communicated.</p>
            <h2>Forced Communication</h2>
            <p>I can effectively communicate what its like to have a conscious experience by forcing you to have the same one. Very simply, I can make you taste the same thing as me by sharing my food. Do I have any guarentee that it tastes the same to you? Not at all, but I can be assured that we now both have an understanding of what that food tastes like. I can show you red, I can stab you, I can play a sound. These are all ways that I can cause you to experience something consciously, without using words. There is a shortcoming to this: it still doesn't work for someone who can't experience these things. Due to this, conscious experiences must be incommunicable to some degree.</p>
            <p>Perhaps this is in fact an obvious conclusion: conscious experiences can only be understood by experiencing them! Is there anything else in the world that is like this though? Is there anything else in the world?</p>
            <h2>Conscious Experiences are Everything</h2>
            <p>Imagine an object. Whatever you just imagined, you imagined through the lens of consciously experiencing it. You imagined seeing, touching, smelling, hearing, or tasting it. Its impossible to imagine a physical object without invoking consciousness. Therefore, it is impossible to communicate information about a physical object such that someone who hasn't seen it can imagine it. This can't be true, obviously. We can communicate ideas about objects that don't exist, or ones we've never experienced, but we have to start with things we have experienced. There's no way to get around this. You can't describe an object without using physical senses.</p>
            <h2>Conscious Experiences Can't be Everything</h2>
            <p>But you actually <i>can</i> describe objects without invoking consciousness. Say I give you the following equation:</p>
            <h3>x² + y² + z² = 4</h3>
            <p>I have just described a sphere without invoking conscious experience. Its not a <i>real</i> object, but it is an object. Does it solve the incommunicability problem? In a way, yes. You don't need to have seen a sphere before to graph this equation and create one. Without <i>seeing</i> the graph of the equation, we can <i>know</i> that its a sphere. Maybe I can get platonic here. This equation <i>is</i> a sphere, and any conscious experience that percieves a sphere is simply translating that into something a human understands.</p>
            <h2>Conscious Experience as Translation</h2>
            <p>If a conscious experience is the translation of the objective to the subjective, does that make it make any more sense? I think so. As I look around the world, I see lots of things, trees, clouds, buildings, cars, etc. But what are those things in an objective sense? They are not cars, buildings, clouds, or trees; they are collections of atoms, molecules, cells, and structures. It is almost unfathomable to imagine seeing the world this way. When I look at my favorite example, the apple, how could I see anything except an apple? Objectively, however, there is no apple. It is the job of my senses to <i>create</i> the concept of the apple and apply it to the bundle of atoms, molecules, and cells that I am looking at. Thus, of course it is impossible to communicate this to someone else! My senses made it for <i>me</i>! If I want to communicate what I think an apple is, I necessarily have to point at the objective thing and let others' senses do the same. If I want to communicate the objective phenomenom that I call an apple, I have to use things that avoid conscious experience.</p>
            <h2>How to Communicate Objective Things</h2>
            <p>Math (or more broadly, numbers) is the way we communicate objective things. If I want to objectively describe the phenomenon that my senses percieve as red, I can simply write about light with a wavelength of 700 nanometers. Like the equation for the sphere, there is no way to describe the translation of that to my experience of red, but that is because light with a wavelength of 700 nm <i>is</i> red. My experience of it is irelevant. Thus, my earlier postulations about forced communication has to be the only way to communicate conscious experience.</p>
            <h2>A Deep Pit</h2>
            <p>And yet, there is more to wonder. Why does my experience of red look the way it does? Perhaps this is the real question that lurks at the heart of this write up. It is deeply unsatisfying to say that the translating my senses do is in some way unknowable, or indescribable. What if I want someone to understand <i>my</i> experience of red, not theirs? Could it be that it is impossible? Its hard for me to say. On the one hand, the optimist in me says that nothing is indescribable, and that science will one day reach even this corner of reality. On the other hand, the pessimist in me says that science was explicitly formulated to study the objective world and it will fail to tell us anything about our own subjective experiences. In the meantime, we will have to communicate by trusting that we are experiencing something similar, and not knowing why.</p>
            <h2>Clawing Out of the Pit</h2>
            <p>If I'm unsatisfied with my position, why should I stop thinking about it? Clearly I shouldn't. I'm satisfied with my understanding of what conscious experiences are (translations of objective to subjective), but something is obviously missing. What is a subjective experience? Perhaps this is the problem I need to solve to be satisfied.</p>
            <h3>Illusionism</h3>
            <p>Illusionism is the most materialistic answer to the question of what consciousness is: it is an illusion. This is the position Hofstadter takes in <i>I am a Strange Loop</i>. Is consciousness real? Illusionists would say "Yes, consciousness is real, but only in the same way a mirage is real". What is worth considering is this: is consciousness the mirage, or is it the image that the mirage produces? Secondly, who is the observer of the mirage?</p>
            <p>If consciousness were simply the mirage, it would have to be real. Not just "meta-real" or something, but really, physically real. An objective observer could pin point the exact area a mirage is occuring in by measuring air pressure differentials and so on. Therefore, consciousness must be the image produced by the mirage. This makes more sense. The objective phenomenom is the brain and its states, while the image that produces is consciousness.</p>
            <p>But how does a mirage's image know itself? You know things, feel things, and are things that a mirage's image never could. But this is where the illusion aspect comes into play. "You" don't know or feel any of these things, your brain does. Like the air pressure differentials shifting to change the mirage's image, "you" change with your brain's changing states. Does this <i>have</i> to mean you aren't real? In my view, no. I'm still developing this idea, and I will probably write more about it in the future. For now, I think my layers of abstraction write up has some bearing here.</p>
            <h3>Dualism</h3>
            <p>Dualism is a much more simple and intuitive way to look at consciousness. "You" are a soul, or maybe some sort of ambiguous essence, seperate from your body and physical reality. You communicate with your body to do things.</p>
            <p>I don't have much more to say to describe dualism. It is almost the default stance because it is simple and comforting, yet I have issues with it. I have two arguments against dualism, one of which I admit is probably weak, and the other is adapted from Philip Goff's arguments in <i>Galileo's Error</i>.</p>
            <p>Human intuition tends to be wrong when it comes to fundamental aspects of reality. Ask someone two thousand years ago about the fundamental nature of the universe and they would be completely, unequivocally, wrong. Not their fault! But they would be wrong. Why then, do we assume that they would be right about the soul? To assume this is to assume that we come pre-equipped with an understanding of our own existence. I dont know about you, but I don't know what I am. Dualism should be considered simply as an option among many, and not the default one that needs to be replaced.</p>
            <p>That was my feelings on my dualism, now here is an adaptation of Goff's argument, called the interaction problem.</p>
            <h4>God and Doctors</h4>
            <p>Say we lived in a world where God intervened regularly to heal human bodies. Broken bones, cancer, mental illness, all of it. Doctors would be aware of this and would consider it as a factor when treating patients. When God does this healing, we could call it an <i>anomolous event</i>. It is a physical effect (mending bones, healing cancer) with a non-physical cause (God). We don't live in this world, obviously. Licensed medical doctors don't pray to God to heal their patients, rather they do the best they can with physical tools. Doctor's don't expect anomolous events (physical effects with non-physical causes) in their patients.</p>
            <h4>Occam's Razor</h4>
            <p>Occam's Razor is a fundamental law in scientific reasoning that says "If two models make the exact same predictions, the one with less entities should be held to be true." Say we had two models: the standard model, and the angelic model. The standard model of physics makes accurate predictions about the universe. The angelic model makes the exact same, identical predictions, but it also posits the existence of an impotent angel that observes the universe. The angel has no power to cause any effects or alter the model's predictions. Occam's razor tells us that, even though they make the same exact predictions, we should go with the standard model, since it is simpler!</p>
            <h4>Tying it Together</h4>
            <p>Lets look at the brain now. Within the brain, there have been no anomolous events (that is, physical effects with non-physical causes) found up to this point. Neuroscientists don't consider souls, or non-physical causes, when studying the brain, because they have had no reason to suspect its existence, because they have never observed these anomolous events.</p>
            <p>So, we are trying to explain what consciousness is. We have two types of models that explain events in the brain (which are correlated with consciousness), Dualism and Non-Dualism. They both necessarily must make the same predictions that are consistent with events that we observe in the brain. One of them, Dualism, posits that these events exist and have physical causes (because we know they do), but that there is a powerless external soul observing them. Non-Dualism also posits that that these events are happening (because it must!) but it does not posit the existence of the impotent angel.</p>
            <p>By Occam's Razor, we must assume that non-dualism is the true solution, since they both make the same predictions about events in the brain, but one posits more entities than the other.</p>
            <h4>My Thoughts</h4>
            <p>Illusionism doesn't suffer these same problems as dualism. It actually does the reverse of dualism: it aligns itself most consistently with what we can observe. In illusionism, only what we observe is real. Perhaps one day, we will discover an event in the brain without a physical cause, and we can say then that Dualism more accurately predicts what we observe.</p>
            <p>I do admit that I didn't challenge Illusionism enough. If you have any ideas that knock down illusionism, let me know!</p>
        </div>

      
    </StarPanel>
  );
}
